### PR TITLE
Replace hardcoded values

### PR DESCRIPTION
**Pull request by joerggollnick**
This should implement #5

### CODE REVIEW

**Comment by gjtorikian** [comment]
Ah, I see. Yes, I think I'm in favor of this.

For backwards compatibility I think the third option should be optional (if you want to set different configurations). Also it looks like some tests broke.

**Comment by axilleas** [comment]
@joerggollnick :wave: you think you have some time to finish this? :heart: 

I stumbled upon the hardcoded output path.

**Comment by joerggollnick** [comment]
@axilleas I tried to make the config optional. But I have no time to test the code beside test cases and my productive install.

**Comment by axilleas** [comment]
> @axilleas I tried to make the config optional. But I have no time to test the code beside test cases and my productive install.

Thank you!

@gjtorikian does this look ok? :)

**Comment by gjtorikian** [comment]
Because I was not allowed to push onto the fork, I ended up forking this PR and creating a new one with tests: https://github.com/gjtorikian/nanoc-redirector/pull/10

If it passes, I will merge and release it. Thanks for the contribution!

**Pull request closed without merging**
